### ISSUE TITLE
Issue with pip install size_constrained_clustering

### ISSUE THREAD

**Issue by HediHargam** [jingw2/size_constrained_clustering#2]
Hello, 

First of all, great work and nice repository !

However, I have an issue when i try to install with pip. I have this error message : 

ValueError: '/tmp/pip-install-hztjsh5l/size-constrained-clustering_0f0eaa2d194b40909287b3e66a4ceeb5/size_constrained_clustering/k_means_constrained/mincostflow_vectorized_.pyx' doesn't match any files

I think it come from cython dependencies, and/or with 'pyx' extensions in setup.py

I can however use pip install git+https://github.com/jingw2/size_constrained_clustering (it works) but it's quit difficult then for pip to resolve dependency with other libraries.

Has anyone ever had the same issue before?

**Comment by bohanwu2000** [comment]
I have the same issue.

**Comment by jingw2** [comment]
I will fix that issue soon

**Comment by EricPostMaster** [comment]
I'm having the same issue, but I'm not able to get it to work with `pip install git+https://github.com/jingw2/size_constrained_clustering` like @HediHargam. I added `--user` and still got errors. Any suggestions?

**Comment by jmlarson1** [comment]
I am also having this issue with clustering_d464fd0903904d20867af7efe88f177d/size_constrained_clustering/k_means_constrained/mincostflow_vectorized_.pyx

**Comment by jingw2** [comment]
Hi, all, I guess the main problem is from version. I used Python 3.6 to develop. 
Python 3.6 installing still worked but when I applied Python 3.7 to install, the problem appeared.

**Comment by cjmateos** [comment]
Hi,

I tried to install it on Docker using different versions of python (3.6, 3.7, 3.8 and 3.9) and it fails when I try to install from pip

```
$ docker run -it python:3.6-buster bash

root@82ff32d4be50:/# python -V
Python 3.6.14

root@82ff32d4be50:/# pip install size-constrained-clustering
Collecting size-constrained-clustering
  Downloading size_constrained_clustering-0.1.1.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 1.1 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/setup.py'"'"'; __file__='"'"'/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a049ykxt
         cwd: /tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/setup.py", line 63, in <module>
        extensions = cythonize(extensions, compiler_directives=compiler_directives)
      File "/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/.eggs/Cython-0.29.24-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 972, in cythonize
        aliases=aliases)
      File "/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/.eggs/Cython-0.29.24-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/.eggs/Cython-0.29.24-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: '/tmp/pip-install-de6gl_ue/size-constrained-clustering_28478f8ae3d64cca9978330fa5619d95/size_constrained_clustering/k_means_constrained/mincostflow_vectorized_.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/a2/eb43a58139986f3280b378125b850a33d663021426f202027720fd080e6a/size_constrained_clustering-0.1.1.tar.gz#sha256=27acf88ea48ed5b8690f1f0869ecfb28da805bdd86cb3d9b37a9eceaa9b9908a (from https://pypi.org/simple/size-constrained-clustering/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement size-constrained-clustering (from versions: 0.1.1)
ERROR: No matching distribution found for size-constrained-clustering
```

**Comment by winston01** [comment]
Same error here, works with @HediHargam 's solution (using gitlab as source).

**Comment by cjmateos** [comment]
The issue seems to be that the package uploaded to PyPI is broken.

Installing the package from the Github repo and using the tag v0.1.1 it works!   

```
pip install git+https://github.com/jingw2/size_constrained_clustering@v0.1.1
```

**Comment by Hassan6678** [comment]
In my case when I used
`pip install size_constrained_clustering`
not working on the **Window** and I also try on **Ubuntu**

after that when I used 
`pip install git+https://github.com/jingw2/size_constrained_clustering@v0.1.1`
it working on google **Colab**
and Window with **python version 3.6**

**Comment by danvip10** [comment]
I also have this issue, has a workaround been found? Unfortunately I cannot install via github from the machine I'm working on.

**Comment by anonymously123456** [comment]
I still have this issue and my python version is 3.6. 
pip install git+https://github.com/jingw2/size_constrained_clustering@v0.1.1     this is not work，could you please tell me the reason？

**Comment by AlbertPlaPlanas** [comment]
It seems the problem is when installing matplotlib. 

I've noticed there's one fork of the repo in which a user  ( @knasti ) has removed matplotlib dependencies and then it works:
You could install from there using `git+https://github.com/knasti/size_constrained_clustering`

**Comment by varshitha021** [comment]
when i use this git+https://github.com/knasti/size_constrained_clustering
![Screenshot 2023-07-06 122106](https://github.com/jingw2/size_constrained_clustering/assets/113669975/e4598bd0-864e-463e-b5ad-e1d1a9c1a1d1)

**Comment by OlegVasilyev4096** [comment]
Also problem installing.    pip install size-constrained-clustering

Collecting size-constrained-clustering
  Using cached size_constrained_clustering-0.1.1.tar.gz (52 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xw/nv8rc6nj4vnc4gncwcrs3s1h0000gp/T/pip-install-_6__3izb/size-constrained-clustering_a0f022cf99a74c0abb8531a512f818b0/setup.py", line 63, in <module>
          extensions = cythonize(extensions, compiler_directives=compiler_directives)
        File "/opt/homebrew/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 973, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/opt/homebrew/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/opt/homebrew/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: '/private/var/folders/xw/nv8rc6nj4vnc4gncwcrs3s1h0000gp/T/pip-install-_6__3izb/size-constrained-clustering_a0f022cf99a74c0abb8531a512f818b0/size_constrained_clustering/k_means_constrained/mincostflow_vectorized_.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by AlbertPlaPlanas** [comment]
@varshitha021 and @OlegVasilyev4096 
As I faced issues with the package and I just needed the Deterministic Annealing Clustering implementation, I forked and released a package that just contained that class & method. Maybe it can help:

https://github.com/AlbertPlaPlanas/size_constrained_clustering
https://pypi.org/project/light-size-constrained-clustering/

**Comment by varshitha021** [comment]
Subject: Thank You for Your Help and an Update on My Progress

Dear Albert Palmaplanas,

I hope this email finds you well. I am writing to express my gratitude
for your assistance in my clustering problem. Your support was
instrumental in my decision to take matters into my own hands and find
a solution.

However, I wanted to share some doubts I encountered during my
implementation process. The primary concern was assigning appropriate
values to the distribution list for the clustering algorithm. In my
case, I have 22,448 data points that I wanted to cluster into 92
equal-sized clusters, each containing 244 points. I initially assigned
random values to the distribution list, ensuring their sum was 1.
However, this didn't yield the desired equal-sized clusters.

If you have any insights or suggestions on how I can set the
distribution values more effectively to achieve equal-sized clusters,
I would greatly appreciate your input. I believe your expertise would
be invaluable in refining the clustering process.

Furthermore,In my project,I have to cluster buildings into clusters
while considering various constraints. Specifically, I aim to take
into account constraints such as roads, flyovers, water passages, and
other similar elements that may exist between the buildings. By
incorporating these constraints into the clustering process, I hope to
achieve more meaningful and practical groupings of buildings.

the below image clearly depicts the problem statement for my project



Once again, I sincerely thank you for your assistance, and I look
forward to hearing from you soon.

Best regards,
Minumula Varshitha

**Comment by varshitha021** [comment]
Dear  Albert Palmaplanas,

I hope this email finds you well. I wanted to express my heartfelt
appreciation for your prompt and helpful response to my query. Your
guidance on installation of the package was truly instrumental in
completing my task successfully.

Thanks to your assistance, I was able to implement the required
changes in my code and achieve the desired outcome. Your support made
a significant difference in my project, and I am extremely grateful
for your expertise and willingness to help.

As I continue to work on my project, I find myself facing another
intriguing challenge that I believe your expertise could greatly
benefit. My current focus is on road constraint clustering, where I
aim to cluster buildings while considering constraints such as roads,
flyovers, water passages, and other road-related elements that may
exist between the buildings.

I would be immensely grateful if you could share your insights on the
best approaches, algorithms, or methodologies that can effectively
incorporate road constraints into the clustering process.
Additionally, any guidance on feature engineering, preprocessing
techniques, and relevant research papers or resources would be
incredibly valuable.


Once again, thank you for your time and valuable input. Your
assistance has been invaluable, and I cannot emphasize enough how much
I appreciate your help.

Please do not hesitate to reach out if you ever need any assistance or
have any questions. I am more than willing to return the favor and
offer my support.

With sincerest gratitude,
Minumula Varshitha

**Comment by sight007** [comment]
It's 2023.08， the same issue hasn't been fixed yet......

**Comment by varshitha021** [comment]
not yet fixed
